#pragma once

#define _USE_MATH_DEFINES
#include <math.h>

namespace engine
{
	const float PI = (float)M_PI;           // PI = 3.14...
	const float TWO_PI = 2 * PI;            // 2 * PI = 6.28...
	const float HALF_PI = (float)M_PI_2;    // PI / 2 = 1.57...
	const float QUARTER_PI = (float)M_PI_4; // PI / 4 = 0.78...
}
